name: prod

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Deploy"
        default: "Deploy"
        required: false

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      - name: Change directory to project folder
        run: cd /home/ubuntu/3d-editor/photoscope-editor

      - name: Pull the latest code from main
        run: git pull origin main

      - name: Install dependencies
        run: npm install

      - name: Restart Application
        run: pm2 restart index.html
