name: prod

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Deploy"
        default: "Deploy"
        required: false

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start/Restart http-server
        run: pm2 restart http-server
