name: prod

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Deploy"
        default: "Deploy"
        required: false

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start/Restart http-server on port 5000
        run: |
          pm2 describe http-server > /dev/null && pm2 restart http-server -- -p 5000 || pm2 start http-server --name http-server -- -p 5000
